# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Luis Mayta <@slovacus>

# Copy custom configuration file from the current directory
COPY conf/nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80
